version: '3.1'

services:
  tasker_pg:
    image: postgres:15.4
    container_name: tasker_pg
    restart: always
    environment:
      POSTGRES_DB: taskerdb
      POSTGRES_USER: josue
      POSTGRES_PASSWORD: secret1234
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - 5432:5432