version: '3.1'

services:
  tasker_pg:
    image: postgres:15.4
    container_name: tasker_pg
    restart: always
    environment:
      - POSTGRES_DB: tasker_db
      - POSTGRES_USER: josue
      - POSTGRES_PASSWORD: admin